[package]
name = "chibitest"
version = "0.1.0"
authors = ["Brandon Matthews <bmatthews@zipcar.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"
#bindgen = "0.26.3"

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }

[features]
# Set a default chip like so. N.B. that specifying --feature on the command line
#  will *add* to the default, and not override it.
#default = ["stm32f051x8"]

stm32f051x8 = []
stm32f407xg = []
